FROM ubuntu:18.04

WORKDIR /

RUN apt-get update -y

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    apt-utils \
    build-essential \                                                               
    cmake \                                                                         
    curl \                                                                          
    git \
    libcurl3-dev \                                                                  
    libgoogle-glog-dev \                                                            
    libfreetype6-dev \                                                              
    libpng-dev \                                                                    
    libprotobuf-dev \                                                               
    libzmq3-dev \                                                                   
    pkg-config \                                                                    
    protobuf-compiler \                                                             
    libprotoc-dev \                                                                 
    rsync \                                                                         
    software-properties-common \                                                    
    unzip \                                                                         
    zip \                                                                           
    zlib1g-dev \                                                                    
    openjdk-8-jdk \                                                                 
    openjdk-8-jre-headless \                                                        
    openssh-server \                                                                
    openssh-client \                                                                
    wget \                                                                          
    bsdmainutils \                                                                  
    ccache \                                                                        
    libssl-dev \                                                                    
    gcovr \                                                                         
    bc

RUN bash -x docker/installs/install_zsh.sh

# Should install zsh before vim
RUN bash -x docker/installs/install_vim.sh

RUN bash -x docker/installs/install_tmux.sh

# Install bazelisk
ENV BAZELISK_VERSION v1.11.0
RUN wget -q https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-linux-amd64 && \
    chmod +x bazelisk-linux-amd64 && \
    mv ./bazelisk-linux-amd64 /usr/local/bin/bazelisk
